{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kube-token-exchanger.fullname" . }}
  labels:
    {{- include "kube-token-exchanger.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - serviceaccounts/token
    verbs:
      - create
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - tokenexchange.aldershaab-it.dk
    resources:
      - tokenexchangerequests
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - tokenexchange.aldershaab-it.dk
    resources:
      - tokenexchangerequests/finalizers
    verbs:
      - update
  - apiGroups:
      - tokenexchange.aldershaab-it.dk
    resources:
      - tokenexchangerequests/status
    verbs:
      - get
      - patch
      - update
{{- end }}
