apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kube-token-exchanger.fullname" . }}
  namespace: {{ include "kube-token-exchanger.namespace" . }}
  labels:
    {{- include "kube-token-exchanger.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kube-token-exchanger.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kube-token-exchanger.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kube-token-exchanger.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
        - name: operator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            {{- if .Values.args.leaderElect }}
            - --leader-elect
            {{- end }}
            - --metrics-bind-address={{ .Values.metrics.bindAddress }}
            - --health-probe-bind-address={{ .Values.health.bindAddress }}
          ports:
            - name: metrics
              containerPort: {{ trimPrefix ":" .Values.metrics.bindAddress }}
            - name: health
              containerPort: {{ trimPrefix ":" .Values.health.bindAddress }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
