{{- if .Values.metrics.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-token-exchanger.fullname" . }}-metrics
  namespace: {{ include "kube-token-exchanger.namespace" . }}
  labels:
    {{- include "kube-token-exchanger.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metrics.service.type }}
  selector:
    {{- include "kube-token-exchanger.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.metrics.service.port }}
      targetPort: metrics
{{- end }}
