apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-token-exchanger
  namespace: kube-token-exchanger
  labels:
    app.kubernetes.io/name: kube-token-exchanger
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-token-exchanger
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kube-token-exchanger
    spec:
      serviceAccountName: kube-token-exchanger
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: operator
          image: ghcr.io/lukaspj/kube-token-exchanger:latest
          args:
            - --leader-elect
          ports:
            - name: metrics
              containerPort: 8080
            - name: health
              containerPort: 8081
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
