name: Build and test

on:
  pull_request:
    paths:
      - "**/*.go"
      - go.mod
      - go.sum
  push:
    branches:
      - main
    paths:
      - "**/*.go"
      - go.mod
      - go.sum

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Vet
        run: go vet ./...

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -race -coverprofile=coverage.out ./...

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.out

      - name: Render manifests
        run: make manifests
